stages:
  - prepare
  - test
  - publish

prepare:
  stage: prepare
  image: node:10.15.3-alpine
  cache:
    paths:
      - node_modules
  script:
    - yarn install
  tags:
    - sl-frontend

lint:
  stage: test
  image: node:10.15.3-alpine
  cache:
    paths:
      - node_modules
  script:
    - yarn lint
  tags:
    - sl-frontend

test:
  stage: test
  image: node:10.15.3-alpine
  cache:
    paths:
      - node_modules
  script:
    - yarn test
  tags:
    - sl-frontend

publish-package:
  stage: publish
  image: node:10.15.3-alpine
  cache:
    paths:
      - node_modules
  before_script:
    - echo //gitlab.sima-land.ru/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN} > .npmrc
    - npm version $CI_COMMIT_REF_NAME
    - yarn build
  script:
    - npm publish build
  only:
    refs:
      - tags
  tags:
    - sl-frontend

badge_release:
  stage: publish
  image: python:3.6
  before_script:
    - echo "Python other dependencies installation"
    - pip install anybadge
  script:
    - anybadge -l "release" -v "$CI_COMMIT_TAG" -f release-version.svg -c green
  artifacts:
    paths:
      - release-version.svg
    expire_in: 4 weeks
  only:
    refs:
      - tags
  tags:
    - sl-frontend