name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run lint
          npm run type-check

      - name: Unit tests
        run: npm run test -- --coverage --forceExit

      - name: Package tests
        working-directory: ./package-tests
        run: |
          npm i
          npm run preparing
          npm run test
